version: "3.9"

services:
  zx9999:
    build: .
    command: python manage.py runserver 0.0.0.0:9999
    ports:
      - "9999:9999"
    volumes:
      - .:/app
    environment:
      DEBUG: "1"
      ALLOWED_HOSTS: "0.0.0.0,127.0.0.1,localhost"
